### ISSUE TITLE
IOB Annotation on NCBI & BC2

### ISSUE THREAD

**Issue by leobouscarrat** [valdersoul/GRAM-CNN#8]
Hello,

In the eng files of BC2 and NCBI I saw that there is no B but only O and I, is it handled later?

Example in ncbi/dev.eng line 17-21:

```shell
causing VBG O
severe JJ O
enzyme JJ I-UN
deficiency NN I-UN
. . O
```

Also, does it affect the F1-score, I'm not entirely sure of how it is computed for this datasets.

Thanks.

**Comment by valdersoul** [comment]
Hi,

Yes, it's handled later. The code is [here](https://github.com/valdersoul/GRAM-CNN/blob/6caa40e3ea105d5f84ebb9a3aa7fa5dcc4bca266/src/loader.py#L32).

We use the IOBES for all the experiments.

**Comment by leobouscarrat** [comment]
Thanks for the answer.
